-- 컨벤션 예시: 스키마는 Flyway 마이그레이션으로만 관리하고, JPA ddl-auto 는 validate 로 검증만 한다.
-- 파일명 규칙: V<버전>__<설명>.sql (예: V2__add_sample_status.sql)

create table sample (
    id         bigint generated by default as identity primary key,
    name       varchar(100) not null,
    created_at timestamp    not null,
    updated_at timestamp    not null
);
